#include <time.h>

#include "shift_rows_layer.h"
#include "sub_bytes_layer.h"
#include "mix_columns_layer.h"
#include "add_round_key_layer.h"

/* global variables */
const char * input_matrix_file_name = "input_matrix.txt";
const char * output_matrix_file_name = "output_matrix.txt";
const char * output_master_key_file_name = "master_key.txt";

/* helper functions */
/*************************************************************************************
 *  read an input matrix from the file specified by the varialbe <input_matrix_file_name>
 *  @param input)matrix: the header pointer of the 128 bits input texts
 *                  <inputs>[i] (i=0-15) represents one byte
 *                  <inputs>[4k] (k=0-3) represents the header for the kth row
 *************************************************************************************/
void Read_Marix_From_File( unsigned char * input_matrix );

/*************************************************************************************
 *  store the contents in <input_matrix> in the file specified by the variable 
 *                  <output_matrix_file_name>
 *  @param inputs: the header pointer of the 128 bits input texts
 *                  <inputs>[i] (i=0-15) represents one byte
 *                  <inputs>[4k] (k=0-3) represents the header for the kth row
 *************************************************************************************/
void Print_Result_Matrix_To_File( const unsigned char * input_matrix );

/*************************************************************************************
 *  initialize the master key using random numbers generated by c
 *  @param master_key: the header pointer of the 128 bits master key
 *                  <inputs>[i] (i=0-15) represents one byte
 *                  <inputs>[4k] (k=0-3) represents the header for the kth row
 *************************************************************************************/
void Initialize_Master_Key( unsigned char * master_key );

/*************************************************************************************
 *  store the contents in <master_key> in the file specified by the variable 
 *                  <output_master_key_file_name>
 *  @param master_key: the header pointer of the 128 bits master key
 *                  <inputs>[i] (i=0-15) represents one byte
 *                  <inputs>[4k] (k=0-3) represents the header for the kth row
 *************************************************************************************/
void Print_Master_Key_To_File( const unsigned char * master_key );

int main()
{
    /* declarations */
    unsigned char   input_matrix[16] = { 0 };
    unsigned char   master_key[16] = { 0 };
    unsigned char   key_buffer[16] = { 0 };
    unsigned char   whole_key[4*44] = { 0 };
    unsigned int    round = 0;

    /* initialize master key randomly */
    Initialize_Master_Key( master_key );

    /* write master key into the file */
    Print_Master_Key_To_File( master_key );

    /* generate the whole key set */
    Generate_Key( master_key, whole_key );

    /* read the input matrix from the file */
    Read_Marix_From_File( input_matrix );

    /* first AddRoundkey operation */
    Extract_Ith_Key( whole_key, round, key_buffer );
    Add_Round_Key( input_matrix, key_buffer );
    round ++;   /* round = 1 */

    /* repeat all operations for 9 times */
    while ( round <= 9 )
    {
        /* do the SubBytes layer */
        Sub_Bytes( input_matrix );

        /* do the ShiftRows layer */
        Shift_Rows( input_matrix );

        /* do the MixColumns layer */
        Mix_Columns( input_matrix );

        /* do the AddRoundKey layer */
        Extract_Ith_Key( whole_key, round, key_buffer );
        Add_Round_Key( input_matrix, key_buffer );
        round ++;
    }

    /* final round */
    /* do the SubBytes layer */
    Sub_Bytes( input_matrix );

    /* do the ShiftRows layer */
    Shift_Rows( input_matrix );

    /* do the AddRoundKey layer */
    Extract_Ith_Key( whole_key, round, key_buffer );
    Add_Round_Key( input_matrix, key_buffer );
    round ++;

    /* write the output matrix to the file */
    Print_Result_Matrix_To_File( input_matrix );
    
    return 0;
}

void Read_Marix_From_File( unsigned char * input_matrix )
{
    /* declarations */
    char            buffer;
    unsigned int    entry_iterator = 7;
    unsigned int    entry_counter = 0;

    /* open the file to read the input matrix */
    FILE * file_handler = fopen( input_matrix_file_name, "r" );
    if ( file_handler == NULL )
    {
        printf( "main: file %s cannot be opened!\n", input_matrix_file_name );
        exit( 0 );
    }

    /* read the contents and store them into <input_matrix> */
    while ( ( buffer = fgetc( file_handler ) ) != EOF )
    {
        if ( buffer == ' ' || buffer == '\n' )
        {
            entry_iterator = 7;
            entry_counter ++;
            continue;
        }
        input_matrix[entry_counter] += buffer == 1 ? ( 1 << entry_iterator ) : 0;
        entry_iterator --;
    }
    fclose( file_handler );
    return;
}

void Print_Result_Matrix_To_File( const unsigned char * output_matrix )
{
    /* declaration */

    /* open the file to read the input matrix */
    FILE * file_handler = fopen( output_matrix_file_name, "w+" );
    if ( file_handler == NULL )
    {
        printf( "main: file %s cannot be opened!\n", output_matrix_file_name );
        exit( 0 );
    }

    /* write the output matrix to the file */
    for ( int i = 0; i < 16; ++i )
    {
        for ( int j = 7; j >= 0; --j )
        {
            int bit = ( output_matrix[i] >> j ) & 01;
            if ( bit == 0 )
            {
                fputc( '0', file_handler );
            }
            else
            {
                fputc( '1', file_handler );
            }
        }
        if ( i % 4 == 3 )
        {
            fputc( '\n', file_handler );
        }
        else
        {
            fputc( ' ', file_handler );
        }
    }
    return;
}

void Initialize_Master_Key( unsigned char * master_key )
{
    if ( master_key == NULL )
    {
        printf( "Initialize_Master_Key: null input!\n" );
        exit( 0 );
    }

    srand( time( 0 ) );
    for ( int i = 0; i < 16; ++i )
    {
        master_key[i] = rand() & ( (1 << 8) - 1 );
    }
    return;
}

void Print_Master_Key_To_File( const unsigned char * master_key )
{
    /* declaration */

    /* open the file to read the input matrix */
    FILE * file_handler = fopen( output_master_key_file_name, "w+" );
    if ( file_handler == NULL )
    {
        printf( "main: file %s cannot be opened!\n", output_master_key_file_name );
        exit( 0 );
    }

    /* write the master key to the file */
    for ( int i = 0; i < 16; ++i )
    {
        for ( int j = 7; j >= 0; --j )
        {
            int bit = ( master_key[i] >> j ) & 01;
            if ( bit == 0 )
            {
                fputc( '0', file_handler );
            }
            else
            {
                fputc( '1', file_handler );
            }
        }
        if ( i % 4 == 3 )
        {
            fputc( '\n', file_handler );
        }
        else
        {
            fputc( ' ', file_handler );
        }
    }
    return;
}